### ISSUE TITLE
Feature: Named Scopes

### ISSUE THREAD

**Issue by scrogson** [chrismccord/atlas#15]
Thinking about a nice interface for named scopes:

``` elixir
# lib/blog/models/post.ex
defmodule Blog.Models.Post do
  use Atlas.Model
  ...
  scope :published, do: where(is_publised: true)
  ...
end

Blog.Models.Post.published |> Repo.all
```

**Comment by chrismccord** [comment]
My hesitation with scopes is, do they provide anything over just using norma funcs?

``` elixir
defmodule Blog.Models.Post do
  use Atlas.Model
  ...
  def published, do: where(is_publised: true)
  ...
end
```

**Comment by chrismccord** [comment]
I spoke too soon. I guess they could define multiple arities for you, so scopes could be piped. So the question is, is a macro worth the convenience of:

``` elixir
defmodule Blog.Models.Post do
  use Atlas.Model
  ...

  scope :published, do: where(is_publised: true)

  # vs

  def published, do: pubished(scoped)
  def published(scope, options), do: where(scope, is_published: true)
  ...
end
```

**Comment by scrogson** [comment]
Hmmm...yeah, good point. I think I like DSLs too much :smile:

I think the normal function definitions are good enough. Feel free to close.

**Comment by sserdyuk** [comment]
Coming from Rails world, I can't stress enough the importance of named scope support. That's one of the most powerful features of ActiveRecord. It nicely isolates all the business logic at the model level. For example, I'd never use User.where(is_admin: true).all in the controller because that's way too much internal knowledge at this level. Instead, I'd be using User.admins.all, which is concise and much more maintainable. If I needed to update the SQL condition, I'd only need to do it in the scope. The real power comes with using it with associations like: Domain.first.users.admins.all and SQL conditions like Post.where("user.id in (select id from #{User.table_name} where #{User.admins.condition_sql})).all

My point is that, it seems that Atlas has the opportunity adopt these powerful concepts.

And, Chris, answering your question whether it is worth to have a macro to make two lines from one, I'd say "always!". Fewer is always better.

**Comment by scrogson** [comment]
@sserdyuk you can build "scopes" with normal functions with ecto. All of your query functions should receive a "queryable" as the first argument and return a "queryable". This way you can just compose them together with the `|>`
